export const clientProgressData = [
  {
    id: 3920,
    client_name: "rajak recommended3",
    engagement_end_date: "27 December 2023",
    first_session_date: "26 June 2023",
    focus_areas: ["Presenting Effectively", "Thinking Strategically"],
    next_session_date: "27 December 2023",
    session_info: {
      completed_sessions_num: 1,
      remaining_sessions_num: 4,
    },
    company_name: "Pluma 1",
    re_assessment: "Not Opened",
  },
  {
    id: 3573,
    client_name: "rajak dev2",
    engagement_end_date: "28 September 2023",
    first_session_date: "24 March 2023",
    next_session_date: "27 December 2023",
    focus_areas: [],
    session_info: {
      completed_sessions_num: 1,
      remaining_sessions_num: 3,
    },
    company_name: "Pluma 2",
    re_assessment: "In Progress",
  },
  {
    id: 3536,
    client_name: "rajak dev1",
    engagement_end_date: "10 November 2023",
    first_session_date: "22 March 2023",
    next_session_date: "27 December 2023",
    focus_areas: [
      "Delegating",
      "Building the Business Case",
      "Executing Strategies",
      "Presenting Effectively",
    ],
    session_info: {
      completed_sessions_num: 4,
      remaining_sessions_num: 1,
    },
    company_name: "Pluma 3",
    re_assessment: "In Progress",
  },
  {
    id: 3920,
    client_name: "rajak recommended3",
    engagement_end_date: "27 December 2023",
    first_session_date: "26 June 2023",
    focus_areas: ["Presenting Effectively", "Thinking Strategically"],
    next_session_date: "27 December 2023",
    session_info: {
      completed_sessions_num: 1,
      remaining_sessions_num: 4,
    },
    company_name: "Pluma 4",
    re_assessment: "Not Opened",
  },
  {
    id: 3573,
    client_name: "rajak dev2",
    engagement_end_date: "28 September 2023",
    first_session_date: "24 March 2023",
    next_session_date: "27 December 2023",
    focus_areas: [],
    session_info: {
      completed_sessions_num: 1,
      remaining_sessions_num: 3,
    },
    company_name: "Pluma 5",
    re_assessment: "In Progress",
  },
  {
    id: 3536,
    client_name: "rajak dev1",
    engagement_end_date: "10 November 2023",
    first_session_date: "22 March 2023",
    next_session_date: "27 December 2023",
    focus_areas: [
      "Delegating",
      "Building the Business Case",
      "Executing Strategies",
      "Presenting Effectively",
    ],
    session_info: {
      completed_sessions_num: 4,
      remaining_sessions_num: 1,
    },
    company_name: "Pluma 6",
    re_assessment: "In Progress",
  },
  {
    id: 3920,
    client_name: "rajak recommended3",
    engagement_end_date: "27 December 2023",
    first_session_date: "26 June 2023",
    focus_areas: ["Presenting Effectively", "Thinking Strategically"],
    next_session_date: "27 December 2023",
    session_info: {
      completed_sessions_num: 1,
      remaining_sessions_num: 4,
    },
    company_name: "Pluma 7",
    re_assessment: "Not Opened",
  },
  {
    id: 3573,
    client_name: "rajak dev2",
    engagement_end_date: "28 September 2023",
    first_session_date: "24 March 2023",
    next_session_date: "27 December 2023",
    focus_areas: [],
    session_info: {
      completed_sessions_num: 1,
      remaining_sessions_num: 3,
    },
    company_name: "Pluma 8",
    re_assessment: "In Progress",
  },
  {
    id: 3536,
    client_name: "rajak dev1",
    engagement_end_date: "10 November 2023",
    first_session_date: "22 March 2023",
    next_session_date: "27 December 2023",
    focus_areas: [
      "Delegating",
      "Building the Business Case",
      "Executing Strategies",
      "Presenting Effectively",
    ],
    session_info: {
      completed_sessions_num: 4,
      remaining_sessions_num: 1,
    },
    company_name: "Pluma 9",
    re_assessment: "In Progress",
  },
  {
    id: 3920,
    client_name: "rajak recommended3",
    engagement_end_date: "27 December 2023",
    first_session_date: "26 June 2023",
    focus_areas: ["Presenting Effectively", "Thinking Strategically"],
    next_session_date: "27 December 2023",
    session_info: {
      completed_sessions_num: 1,
      remaining_sessions_num: 4,
    },
    company_name: "Pluma 10",
    re_assessment: "Not Opened",
  },
  {
    id: 3573,
    client_name: "rajak dev2",
    engagement_end_date: "28 September 2023",
    first_session_date: "24 March 2023",
    next_session_date: "27 December 2023",
    focus_areas: [],
    session_info: {
      completed_sessions_num: 1,
      remaining_sessions_num: 3,
    },
    company_name: "Pluma 11",
    re_assessment: "In Progress",
  },
  {
    id: 3536,
    client_name: "rajak dev1",
    engagement_end_date: "10 November 2023",
    first_session_date: "22 March 2023",
    next_session_date: "27 December 2023",
    focus_areas: [
      "Delegating",
      "Building the Business Case",
      "Executing Strategies",
      "Presenting Effectively",
    ],
    session_info: {
      completed_sessions_num: 4,
      remaining_sessions_num: 1,
    },
    company_name: "Pluma 12",
    re_assessment: "In Progress",
  },
  {
    id: 3920,
    client_name: "rajak recommended3",
    engagement_end_date: "27 December 2023",
    first_session_date: "26 June 2023",
    focus_areas: ["Presenting Effectively", "Thinking Strategically"],
    next_session_date: "27 December 2023",
    session_info: {
      completed_sessions_num: 1,
      remaining_sessions_num: 4,
    },
    company_name: "Pluma 13",
    re_assessment: "Not Opened",
  },
  {
    id: 3573,
    client_name: "rajak dev2",
    engagement_end_date: "28 September 2023",
    first_session_date: "24 March 2023",
    next_session_date: "27 December 2023",
    focus_areas: [],
    session_info: {
      completed_sessions_num: 1,
      remaining_sessions_num: 3,
    },
    company_name: "Pluma 14",
    re_assessment: "In Progress",
  },
  {
    id: 3536,
    client_name: "rajak dev1",
    engagement_end_date: "10 November 2023",
    first_session_date: "22 March 2023",
    next_session_date: "27 December 2023",
    focus_areas: [
      "Delegating",
      "Building the Business Case",
      "Executing Strategies",
      "Presenting Effectively",
    ],
    session_info: {
      completed_sessions_num: 4,
      remaining_sessions_num: 1,
    },
    company_name: "Pluma 15",
    re_assessment: "In Progress",
  },
  {
    id: 3920,
    client_name: "rajak recommended3",
    engagement_end_date: "27 December 2023",
    first_session_date: "26 June 2023",
    focus_areas: ["Presenting Effectively", "Thinking Strategically"],
    next_session_date: "27 December 2023",
    session_info: {
      completed_sessions_num: 1,
      remaining_sessions_num: 4,
    },
    company_name: "Pluma 16",
    re_assessment: "Not Opened",
  },
  {
    id: 3573,
    client_name: "rajak dev2",
    engagement_end_date: "28 September 2023",
    first_session_date: "24 March 2023",
    next_session_date: "27 December 2023",
    focus_areas: [],
    session_info: {
      completed_sessions_num: 1,
      remaining_sessions_num: 3,
    },
    company_name: "Pluma 17",
    re_assessment: "In Progress",
  },
  {
    id: 3536,
    client_name: "rajak dev1",
    engagement_end_date: "10 November 2023",
    first_session_date: "22 March 2023",
    next_session_date: "27 December 2023",
    focus_areas: [
      "Delegating",
      "Building the Business Case",
      "Executing Strategies",
      "Presenting Effectively",
    ],
    session_info: {
      completed_sessions_num: 4,
      remaining_sessions_num: 1,
    },
    company_name: "Pluma 18",
    re_assessment: "In Progress",
  },
  {
    id: 3920,
    client_name: "rajak recommended3",
    engagement_end_date: "27 December 2023",
    first_session_date: "26 June 2023",
    focus_areas: ["Presenting Effectively", "Thinking Strategically"],
    next_session_date: "27 December 2023",
    session_info: {
      completed_sessions_num: 1,
      remaining_sessions_num: 4,
    },
    company_name: "Pluma",
    re_assessment: "Not Opened",
  },
  {
    id: 3573,
    client_name: "rajak dev2",
    engagement_end_date: "28 September 2023",
    first_session_date: "24 March 2023",
    next_session_date: "27 December 2023",
    focus_areas: [],
    session_info: {
      completed_sessions_num: 1,
      remaining_sessions_num: 3,
    },
    company_name: "Pluma",
    re_assessment: "In Progress",
  },
  {
    id: 3536,
    client_name: "rajak dev1",
    engagement_end_date: "10 November 2023",
    first_session_date: "22 March 2023",
    next_session_date: "27 December 2023",
    focus_areas: [
      "Delegating",
      "Building the Business Case",
      "Executing Strategies",
      "Presenting Effectively",
    ],
    session_info: {
      completed_sessions_num: 4,
      remaining_sessions_num: 1,
    },
    company_name: "Pluma",
    re_assessment: "In Progress",
  },
  {
    id: 3920,
    client_name: "rajak recommended3",
    engagement_end_date: "27 December 2023",
    first_session_date: "26 June 2023",
    focus_areas: ["Presenting Effectively", "Thinking Strategically"],
    next_session_date: "27 December 2023",
    session_info: {
      completed_sessions_num: 1,
      remaining_sessions_num: 4,
    },
    company_name: "Pluma",
    re_assessment: "Not Opened",
  },
  {
    id: 3573,
    client_name: "rajak dev2",
    engagement_end_date: "28 September 2023",
    first_session_date: "24 March 2023",
    next_session_date: "27 December 2023",
    focus_areas: [],
    session_info: {
      completed_sessions_num: 1,
      remaining_sessions_num: 3,
    },
    company_name: "Pluma",
    re_assessment: "In Progress",
  },
  {
    id: 3536,
    client_name: "rajak dev1",
    engagement_end_date: "10 November 2023",
    first_session_date: "22 March 2023",
    next_session_date: "27 December 2023",
    focus_areas: [
      "Delegating",
      "Building the Business Case",
      "Executing Strategies",
      "Presenting Effectively",
    ],
    session_info: {
      completed_sessions_num: 4,
      remaining_sessions_num: 1,
    },
    company_name: "Pluma",
    re_assessment: "In Progress",
  },
  {
    id: 3920,
    client_name: "rajak recommended3",
    engagement_end_date: "27 December 2023",
    first_session_date: "26 June 2023",
    focus_areas: ["Presenting Effectively", "Thinking Strategically"],
    next_session_date: "27 December 2023",
    session_info: {
      completed_sessions_num: 1,
      remaining_sessions_num: 4,
    },
    company_name: "Pluma",
    re_assessment: "Not Opened",
  },
  {
    id: 3573,
    client_name: "rajak dev2",
    engagement_end_date: "28 September 2023",
    first_session_date: "24 March 2023",
    next_session_date: "27 December 2023",
    focus_areas: [],
    session_info: {
      completed_sessions_num: 1,
      remaining_sessions_num: 3,
    },
    company_name: "Pluma",
    re_assessment: "In Progress",
  },
  {
    id: 3536,
    client_name: "rajak dev1",
    engagement_end_date: "10 November 2023",
    first_session_date: "22 March 2023",
    next_session_date: "27 December 2023",
    focus_areas: [
      "Delegating",
      "Building the Business Case",
      "Executing Strategies",
      "Presenting Effectively",
    ],
    session_info: {
      completed_sessions_num: 4,
      remaining_sessions_num: 1,
    },
    company_name: "Pluma",
    re_assessment: "In Progress",
  },
  {
    id: 3920,
    client_name: "rajak recommended3",
    engagement_end_date: "27 December 2023",
    first_session_date: "26 June 2023",
    focus_areas: ["Presenting Effectively", "Thinking Strategically"],
    next_session_date: "27 December 2023",
    session_info: {
      completed_sessions_num: 1,
      remaining_sessions_num: 4,
    },
    company_name: "Pluma",
    re_assessment: "Not Opened",
  },
  {
    id: 3573,
    client_name: "rajak dev2",
    engagement_end_date: "28 September 2023",
    first_session_date: "24 March 2023",
    next_session_date: "27 December 2023",
    focus_areas: [],
    session_info: {
      completed_sessions_num: 1,
      remaining_sessions_num: 3,
    },
    company_name: "Pluma",
    re_assessment: "In Progress",
  },
  {
    id: 3536,
    client_name: "rajak dev1",
    engagement_end_date: "10 November 2023",
    first_session_date: "22 March 2023",
    next_session_date: "27 December 2023",
    focus_areas: [
      "Delegating",
      "Building the Business Case",
      "Executing Strategies",
      "Presenting Effectively",
    ],
    session_info: {
      completed_sessions_num: 4,
      remaining_sessions_num: 1,
    },
    company_name: "Pluma",
    re_assessment: "In Progress",
  },
  {
    id: 3920,
    client_name: "rajak recommended3",
    engagement_end_date: "27 December 2023",
    first_session_date: "26 June 2023",
    focus_areas: ["Presenting Effectively", "Thinking Strategically"],
    next_session_date: "27 December 2023",
    session_info: {
      completed_sessions_num: 1,
      remaining_sessions_num: 4,
    },
    company_name: "Pluma",
    re_assessment: "Not Opened",
  },
  {
    id: 3573,
    client_name: "rajak dev2",
    engagement_end_date: "28 September 2023",
    first_session_date: "24 March 2023",
    next_session_date: "27 December 2023",
    focus_areas: [],
    session_info: {
      completed_sessions_num: 1,
      remaining_sessions_num: 3,
    },
    company_name: "Pluma",
    re_assessment: "In Progress",
  },
  {
    id: 3536,
    client_name: "rajak dev1",
    engagement_end_date: "10 November 2023",
    first_session_date: "22 March 2023",
    next_session_date: "27 December 2023",
    focus_areas: [
      "Delegating",
      "Building the Business Case",
      "Executing Strategies",
      "Presenting Effectively",
    ],
    session_info: {
      completed_sessions_num: 4,
      remaining_sessions_num: 1,
    },
    company_name: "Pluma",
    re_assessment: "In Progress",
  },
  {
    id: 3920,
    client_name: "rajak recommended3",
    engagement_end_date: "27 December 2023",
    first_session_date: "26 June 2023",
    focus_areas: ["Presenting Effectively", "Thinking Strategically"],
    next_session_date: "27 December 2023",
    session_info: {
      completed_sessions_num: 1,
      remaining_sessions_num: 4,
    },
    company_name: "Pluma",
    re_assessment: "Not Opened",
  },
  {
    id: 3573,
    client_name: "rajak dev2",
    engagement_end_date: "28 September 2023",
    first_session_date: "24 March 2023",
    next_session_date: "27 December 2023",
    focus_areas: [],
    session_info: {
      completed_sessions_num: 1,
      remaining_sessions_num: 3,
    },
    company_name: "Pluma",
    re_assessment: "In Progress",
  },
  {
    id: 3536,
    client_name: "rajak dev1",
    engagement_end_date: "10 November 2023",
    first_session_date: "22 March 2023",
    next_session_date: "27 December 2023",
    focus_areas: [
      "Delegating",
      "Building the Business Case",
      "Executing Strategies",
      "Presenting Effectively",
    ],
    session_info: {
      completed_sessions_num: 4,
      remaining_sessions_num: 1,
    },
    company_name: "Pluma",
    re_assessment: "In Progress",
  },
  {
    id: 3920,
    client_name: "rajak recommended3",
    engagement_end_date: "27 December 2023",
    first_session_date: "26 June 2023",
    focus_areas: ["Presenting Effectively", "Thinking Strategically"],
    next_session_date: "27 December 2023",
    session_info: {
      completed_sessions_num: 1,
      remaining_sessions_num: 4,
    },
    company_name: "Pluma",
    re_assessment: "Not Opened",
  },
  {
    id: 3573,
    client_name: "rajak dev2",
    engagement_end_date: "28 September 2023",
    first_session_date: "24 March 2023",
    next_session_date: "27 December 2023",
    focus_areas: [],
    session_info: {
      completed_sessions_num: 1,
      remaining_sessions_num: 3,
    },
    company_name: "Pluma",
    re_assessment: "In Progress",
  },
  {
    id: 3536,
    client_name: "rajak dev1",
    engagement_end_date: "10 November 2023",
    first_session_date: "22 March 2023",
    next_session_date: "27 December 2023",
    focus_areas: [
      "Delegating",
      "Building the Business Case",
      "Executing Strategies",
      "Presenting Effectively",
    ],
    session_info: {
      completed_sessions_num: 4,
      remaining_sessions_num: 1,
    },
    company_name: "Pluma",
    re_assessment: "In Progress",
  },
  {
    id: 3920,
    client_name: "rajak recommended3",
    engagement_end_date: "27 December 2023",
    first_session_date: "26 June 2023",
    focus_areas: ["Presenting Effectively", "Thinking Strategically"],
    next_session_date: "27 December 2023",
    session_info: {
      completed_sessions_num: 1,
      remaining_sessions_num: 4,
    },
    company_name: "Pluma",
    re_assessment: "Not Opened",
  },
  {
    id: 3573,
    client_name: "rajak dev2",
    engagement_end_date: "28 September 2023",
    first_session_date: "24 March 2023",
    next_session_date: "27 December 2023",
    focus_areas: [],
    session_info: {
      completed_sessions_num: 1,
      remaining_sessions_num: 3,
    },
    company_name: "Pluma",
    re_assessment: "In Progress",
  },
  {
    id: 3536,
    client_name: "rajak dev1",
    engagement_end_date: "10 November 2023",
    first_session_date: "22 March 2023",
    next_session_date: "27 December 2023",
    focus_areas: [
      "Delegating",
      "Building the Business Case",
      "Executing Strategies",
      "Presenting Effectively",
    ],
    session_info: {
      completed_sessions_num: 4,
      remaining_sessions_num: 1,
    },
    company_name: "Pluma",
    re_assessment: "In Progress",
  },
  {
    id: 3920,
    client_name: "rajak recommended3",
    engagement_end_date: "27 December 2023",
    first_session_date: "26 June 2023",
    focus_areas: ["Presenting Effectively", "Thinking Strategically"],
    next_session_date: "27 December 2023",
    session_info: {
      completed_sessions_num: 1,
      remaining_sessions_num: 4,
    },
    company_name: "Pluma",
    re_assessment: "Not Opened",
  },
  {
    id: 3573,
    client_name: "rajak dev2",
    engagement_end_date: "28 September 2023",
    first_session_date: "24 March 2023",
    next_session_date: "27 December 2023",
    focus_areas: [],
    session_info: {
      completed_sessions_num: 1,
      remaining_sessions_num: 3,
    },
    company_name: "Pluma",
    re_assessment: "In Progress",
  },
  {
    id: 3536,
    client_name: "rajak dev1",
    engagement_end_date: "10 November 2023",
    first_session_date: "22 March 2023",
    next_session_date: "27 December 2023",
    focus_areas: [
      "Delegating",
      "Building the Business Case",
      "Executing Strategies",
      "Presenting Effectively",
    ],
    session_info: {
      completed_sessions_num: 4,
      remaining_sessions_num: 1,
    },
    company_name: "Pluma",
    re_assessment: "In Progress",
  },
  {
    id: 3920,
    client_name: "rajak recommended3",
    engagement_end_date: "27 December 2023",
    first_session_date: "26 June 2023",
    focus_areas: ["Presenting Effectively", "Thinking Strategically"],
    next_session_date: "27 December 2023",
    session_info: {
      completed_sessions_num: 1,
      remaining_sessions_num: 4,
    },
    company_name: "Pluma",
    re_assessment: "Not Opened",
  },
  {
    id: 3573,
    client_name: "rajak dev2",
    engagement_end_date: "28 September 2023",
    first_session_date: "24 March 2023",
    next_session_date: "27 December 2023",
    focus_areas: [],
    session_info: {
      completed_sessions_num: 1,
      remaining_sessions_num: 3,
    },
    company_name: "Pluma",
    re_assessment: "In Progress",
  },
  {
    id: 3536,
    client_name: "rajak dev1",
    engagement_end_date: "10 November 2023",
    first_session_date: "22 March 2023",
    next_session_date: "27 December 2023",
    focus_areas: [
      "Delegating",
      "Building the Business Case",
      "Executing Strategies",
      "Presenting Effectively",
    ],
    session_info: {
      completed_sessions_num: 4,
      remaining_sessions_num: 1,
    },
    company_name: "Pluma",
    re_assessment: "In Progress",
  },
  {
    id: 3920,
    client_name: "rajak recommended3",
    engagement_end_date: "27 December 2023",
    first_session_date: "26 June 2023",
    focus_areas: ["Presenting Effectively", "Thinking Strategically"],
    next_session_date: "27 December 2023",
    session_info: {
      completed_sessions_num: 1,
      remaining_sessions_num: 4,
    },
    company_name: "Pluma",
    re_assessment: "Not Opened",
  },
  {
    id: 3573,
    client_name: "rajak dev2",
    engagement_end_date: "28 September 2023",
    first_session_date: "24 March 2023",
    next_session_date: "27 December 2023",
    focus_areas: [],
    session_info: {
      completed_sessions_num: 1,
      remaining_sessions_num: 3,
    },
    company_name: "Pluma",
    re_assessment: "In Progress",
  },
  {
    id: 3536,
    client_name: "rajak dev1",
    engagement_end_date: "10 November 2023",
    first_session_date: "22 March 2023",
    next_session_date: "27 December 2023",
    focus_areas: [
      "Delegating",
      "Building the Business Case",
      "Executing Strategies",
      "Presenting Effectively",
    ],
    session_info: {
      completed_sessions_num: 4,
      remaining_sessions_num: 1,
    },
    company_name: "Pluma",
    re_assessment: "In Progress",
  },
  {
    id: 3920,
    client_name: "rajak recommended3",
    engagement_end_date: "27 December 2023",
    first_session_date: "26 June 2023",
    focus_areas: ["Presenting Effectively", "Thinking Strategically"],
    next_session_date: "27 December 2023",
    session_info: {
      completed_sessions_num: 1,
      remaining_sessions_num: 4,
    },
    company_name: "Pluma",
    re_assessment: "Not Opened",
  },
  {
    id: 3573,
    client_name: "rajak dev2",
    engagement_end_date: "28 September 2023",
    first_session_date: "24 March 2023",
    next_session_date: "27 December 2023",
    focus_areas: [],
    session_info: {
      completed_sessions_num: 1,
      remaining_sessions_num: 3,
    },
    company_name: "Pluma",
    re_assessment: "In Progress",
  },
  {
    id: 3536,
    client_name: "rajak dev1",
    engagement_end_date: "10 November 2023",
    first_session_date: "22 March 2023",
    next_session_date: "27 December 2023",
    focus_areas: [
      "Delegating",
      "Building the Business Case",
      "Executing Strategies",
      "Presenting Effectively",
    ],
    session_info: {
      completed_sessions_num: 4,
      remaining_sessions_num: 1,
    },
    company_name: "Pluma",
    re_assessment: "In Progress",
  },
  {
    id: 3920,
    client_name: "rajak recommended3",
    engagement_end_date: "27 December 2023",
    first_session_date: "26 June 2023",
    focus_areas: ["Presenting Effectively", "Thinking Strategically"],
    next_session_date: "27 December 2023",
    session_info: {
      completed_sessions_num: 1,
      remaining_sessions_num: 4,
    },
    company_name: "Pluma",
    re_assessment: "Not Opened",
  },
  {
    id: 3573,
    client_name: "rajak dev2",
    engagement_end_date: "28 September 2023",
    first_session_date: "24 March 2023",
    next_session_date: "27 December 2023",
    focus_areas: [],
    session_info: {
      completed_sessions_num: 1,
      remaining_sessions_num: 3,
    },
    company_name: "Pluma",
    re_assessment: "In Progress",
  },
  {
    id: 3536,
    client_name: "rajak dev1",
    engagement_end_date: "10 November 2023",
    first_session_date: "22 March 2023",
    next_session_date: "27 December 2023",
    focus_areas: [
      "Delegating",
      "Building the Business Case",
      "Executing Strategies",
      "Presenting Effectively",
    ],
    session_info: {
      completed_sessions_num: 4,
      remaining_sessions_num: 1,
    },
    company_name: "Pluma",
    re_assessment: "In Progress",
  },
];

export const clientWithoutFutureSessionsData = [
  {
    client_id: 3536,
    client_name: "rajak dev1",
    company_name: "Pluma 2",
    last_session_date: "24 March 2023",
  },
  {
    client_id: 3573,
    client_name: "rajak dev2",
    company_name: "Pluma 2",
    last_session_date: "24 March 2023",
  },
  {
    client_id: 3920,
    client_name: "rajak recommended3",
    company_name: "Pluma 2",
    last_session_date: "24 March 2023",
  },
];

export const coachData = {
  number_of_clients: 4,
  max_client_limit: 10,
};
