export const upcomingSessions = [
  {
    client_id: "1",
    client_name: "Holly Kulkarni",
    company_name: "PayPal",
    timestamp: "30 Min. call at 6:01 pm, June 30, 2023",
    scheduled_by: "Coach",
    status: "NA",
    engagement_date: "Dec. 26, 2023",
  },
  {
    client_id: "2",
    client_name: "Rollin Cartwright",
    company_name: "Dooley Inc",
    timestamp: "30 Min. call at 6:01 pm, June 30, 2023",
    scheduled_by: "Coach",
    status: "NA",
    engagement_date: "Dec. 26, 2023",
  },
  {
    client_id: "3",
    client_name: "Dr. Justen Mraz",
    company_name: "Morar-Dickinson",
    timestamp: "30 Min. call at 6:01 pm, June 30, 2023",
    scheduled_by: "Coach",
    status: "NA",
    engagement_date: "Dec. 26, 2023",
  },
  {
    client_id: "4",
    client_name: "Raegan Kris",
    company_name: "Steuber, Franecki and Bednar",
    timestamp: "30 Min. call at 6:01 pm, June 30, 2023",
    scheduled_by: "Coach",
    status: "NA",
    engagement_date: "Nov. 20, 2023",
  },
  {
    client_id: "5",
    client_name: "Ara Mann",
    company_name: "Lang-Borer",
    timestamp: "30 Min. call at 6:01 pm, June 30, 2023",
    scheduled_by: "Coach",
    status: "NA",
    engagement_date: "Dec. 26, 2023",
  },
  {
    client_id: "6",
    client_name: "Anthony Beahan III",
    company_name: "Ledner, Connelly and McLaughlin",
    timestamp: "30 Min. call at 6:01 pm, June 30, 2023",
    scheduled_by: "Client",
    status: "NA",
    engagement_date: "Dec. 26, 2023",
  },
  {
    client_id: "7",
    client_name: "Nelson Von Jr.",
    company_name: "Jaskolski, Stokes and Schmeler",
    timestamp: "30 Min. call at 6:01 pm, June 30, 2023",
    scheduled_by: "Client",
    status: "NA",
    engagement_date: "Dec. 26, 2023",
  },
  {
    client_id: "8",
    client_name: "Miss Camille Greenholt IV",
    company_name: "Corwin PLC",
    timestamp: "30 Min. call at 6:01 pm, June 30, 2023",
    scheduled_by: "Coach",
    status: "NA",
    engagement_date: "Dec. 26, 2023",
  },
  {
    client_id: "9",
    client_name: "Ms. Gina Hyatt II",
    company_name: "Hackett-Schuster",
    timestamp: "30 Min. call at 6:01 pm, June 30, 2023",
    scheduled_by: "Client",
    status: "NA",
    engagement_date: "Dec. 26, 2023",
  },
  {
    client_id: "10",
    client_name: "Joannie Considine",
    company_name: "Tremblay-Kulas",
    timestamp: "30 Min. call at 6:01 pm, June 30, 2023",
    scheduled_by: "Coach",
    status: "NA",
    engagement_date: "Dec. 26, 2023",
  },
  {
    client_id: "11",
    client_name: "Eugenia Berge",
    company_name: "Turner and Sons",
    timestamp: "30 Min. call at 6:01 pm, June 30, 2023",
    scheduled_by: "Coach",
    status: "NA",
    engagement_date: "Dec. 26, 2023",
  },
  {
    client_id: "12",
    client_name: "Favian Cronin III",
    company_name: "Aufderhar, Casper and Schumm",
    timestamp: "30 Min. call at 6:01 pm, June 30, 2023",
    scheduled_by: "Client",
    status: "NA",
    engagement_date: "Jan. 2, 2023",
  },
  {
    client_id: "13",
    client_name: "Asha Pollich",
    company_name: "Hagenes LLC",
    timestamp: "30 Min. call at 6:01 pm, June 30, 2023",
    scheduled_by: "Coach",
    status: "NA",
    engagement_date: "Dec. 26, 2023",
  },
  {
    client_id: "14",
    client_name: "Dameon Altenwerth MD",
    company_name: "Hirthe-Durgan",
    timestamp: "30 Min. call at 6:01 pm, June 30, 2023",
    scheduled_by: "Coach",
    status: "NA",
    engagement_date: "Dec. 26, 2023",
  },
  {
    client_id: "15",
    client_name: "Maye Ernser",
    company_name: "Gusikowski-Okuneva",
    timestamp: "30 Min. call at 6:01 pm, June 30, 2023",
    scheduled_by: "Coach",
    status: "NA",
    engagement_date: "Dec. 26, 2023",
  },
  {
    client_id: "16",
    client_name: "Paxton Heidenreich",
    company_name: "Lockman, Haley and Wunsch",
    timestamp: "30 Min. call at 6:01 pm, June 30, 2023",
    scheduled_by: "Client",
    status: "NA",
    engagement_date: "Feb. 14, 2023",
  },
  {
    client_id: "17",
    client_name: "Margot Littel",
    company_name: "Bins PLC",
    timestamp: "30 Min. call at 6:01 pm, June 30, 2023",
    scheduled_by: "Coach",
    status: "NA",
    engagement_date: "Dec. 26, 2023",
  },
  {
    client_id: "18",
    client_name: "Leilani Barton",
    company_name: "Greenfelder-Larson",
    timestamp: "30 Min. call at 6:01 pm, June 30, 2023",
    scheduled_by: "Coach",
    status: "NA",
    engagement_date: "Dec. 26, 2023",
  },
  {
    client_id: "19",
    client_name: "Joyce Haley",
    company_name: "Considine Group",
    timestamp: "30 Min. call at 6:01 pm, June 30, 2023",
    scheduled_by: "Coach",
    status: "NA",
    engagement_date: "Dec. 26, 2023",
  },
  {
    client_id: "20",
    client_name: "Miss Lavonne Leannon Jr.",
    company_name: "Medhurst-Stiedemann",
    timestamp: "30 Min. call at 6:01 pm, June 30, 2023",
    scheduled_by: "Client",
    status: "NA",
    engagement_date: "Dec. 26, 2023",
  },
  {
    client_id: "21",
    client_name: "Prof. Omari Davis V",
    company_name: "Kessler, Lang and Christiansen",
    timestamp: "30 Min. call at 6:01 pm, June 30, 2023",
    scheduled_by: "Coach",
    status: "NA",
    engagement_date: "Mar. 23, 2023",
  },
  {
    client_id: "22",
    client_name: "Buddy Marquardt",
    company_name: "Braun-Ritchie",
    timestamp: "30 Min. call at 6:01 pm, June 30, 2023",
    scheduled_by: "Coach",
    status: "NA",
    engagement_date: "Dec. 26, 2023",
  },
  {
    client_id: "23",
    client_name: "Karlee Gulgowski III",
    company_name: "Murazik and Sons",
    timestamp: "30 Min. call at 6:01 pm, June 30, 2023",
    scheduled_by: "Coach",
    status: "NA",
    engagement_date: "Dec. 26, 2023",
  },
  {
    client_id: "24",
    client_name: "Yvette Walter",
    company_name: "Parisian LLC",
    timestamp: "30 Min. call at 6:01 pm, June 30, 2023",
    scheduled_by: "Client",
    status: "NA",
    engagement_date: "Dec. 26, 2023",
  },
  {
    client_id: "25",
    client_name: "Lenny Herzog",
    company_name: "Blanda and Sons",
    timestamp: "30 Min. call at 6:01 pm, June 30, 2023",
    scheduled_by: "Coach",
    status: "NA",
    engagement_date: "Dec. 26, 2023",
  },
  {
    client_id: "26",
    client_name: "Jude Harris",
    company_name: "Carroll, Windler and Shanahan",
    timestamp: "30 Min. call at 6:01 pm, June 30, 2023",
    scheduled_by: "Coach",
    status: "NA",
    engagement_date: "Dec. 26, 2023",
  },
];

export const previousSessions = [
  {
    client_id: "20",
    client_name: "Joannie Considine",
    company_name: "Tremblay-Kulas",
    timestamp: "30 Min. call at 6:01 pm, June 30, 2023",
    scheduled_by: "Coach",
    status: "Late Cancel",
    engagement_date: "Dec. 26, 2023",
  },
  {
    client_id: "232",
    client_name: "Eugenia Berge",
    company_name: "Turner and Sons",
    timestamp: "30 Min. call at 6:01 pm, June 30, 2023",
    scheduled_by: "Coach",
    status: "Completed",
    engagement_date: "Dec. 26, 2023",
  },
  {
    client_id: "22",
    client_name: "Favian Cronin III",
    company_name: "Aufderhar, Casper and Schumm",
    timestamp: "30 Min. call at 6:01 pm, June 30, 2023",
    scheduled_by: "Client",
    status: "Cancelled",
    engagement_date: "Jan. 2, 2023",
  },
  {
    client_id: "2",
    client_name: "Asha Pollich",
    company_name: "Hagenes LLC",
    timestamp: "30 Min. call at 6:01 pm, June 30, 2023",
    scheduled_by: "Coach",
    status: "Late Cancel",
    engagement_date: "Dec. 26, 2023",
  },
  {
    client_id: "10",
    client_id: "202",
    client_name: "Dameon Altenwerth MD",
    company_name: "Hirthe-Durgan",
    timestamp: "30 Min. call at 6:01 pm, June 30, 2023",
    scheduled_by: "Coach",
    status: "Late Cancel",
    engagement_date: "Dec. 26, 2023",
  },
  {
    client_id: "99",
    client_name: "Maye Ernser",
    company_name: "Gusikowski-Okuneva",
    timestamp: "30 Min. call at 6:01 pm, June 30, 2023",
    scheduled_by: "Coach",
    status: "Completed",
    engagement_date: "Dec. 26, 2023",
  },
  {
    client_id: "23",
    client_name: "Paxton Heidenreich",
    company_name: "Lockman, Haley and Wunsch",
    timestamp: "30 Min. call at 6:01 pm, June 30, 2023",
    scheduled_by: "Client",
    status: "Waiting for feedback",
    engagement_date: "Feb. 14, 2023",
  },
  {
    client_id: "202",
    client_name: "Margot Littel",
    company_name: "Bins PLC",
    timestamp: "30 Min. call at 6:01 pm, June 30, 2023",
    scheduled_by: "Coach",
    status: "Cancelled",
    engagement_date: "Dec. 26, 2023",
  },
  {
    client_id: "55",
    client_name: "Leilani Barton",
    company_name: "Greenfelder-Larson",
    timestamp: "30 Min. call at 6:01 pm, June 30, 2023",
    scheduled_by: "Coach",
    status: "Waiting for feedback",
    engagement_date: "Dec. 26, 2023",
  },
  {
    client_id: "65",
    client_name: "Joyce Haley",
    company_name: "Considine Group",
    timestamp: "30 Min. call at 6:01 pm, June 30, 2023",
    scheduled_by: "Coach",
    status: "Completed",
    engagement_date: "Dec. 26, 2023",
  },
  {
    client_id: "75",
    client_name: "Miss Lavonne Leannon Jr.",
    company_name: "Medhurst-Stiedemann",
    timestamp: "30 Min. call at 6:01 pm, June 30, 2023",
    scheduled_by: "Client",
    status: "Waiting for feedback",
    engagement_date: "Dec. 26, 2023",
  },
  {
    client_id: "88",
    client_name: "Prof. Omari Davis V",
    company_name: "Kessler, Lang and Christiansen",
    timestamp: "30 Min. call at 6:01 pm, June 30, 2023",
    scheduled_by: "Coach",
    status: "Waiting for feedback",
    engagement_date: "Mar. 23, 2023",
  },
  {
    client_id: "77",
    client_name: "Buddy Marquardt",
    company_name: "Braun-Ritchie",
    timestamp: "30 Min. call at 6:01 pm, June 30, 2023",
    scheduled_by: "Coach",
    status: "Waiting for feedback",
    engagement_date: "Dec. 26, 2023",
  },
  {
    client_id: "19",
    client_name: "Karlee Gulgowski III",
    company_name: "Murazik and Sons",
    timestamp: "30 Min. call at 6:01 pm, June 30, 2023",
    scheduled_by: "Coach",
    status: "Waiting for feedback",
    engagement_date: "Dec. 26, 2023",
  },
  {
    client_id: "16",
    client_name: "Yvette Walter",
    company_name: "Parisian LLC",
    timestamp: "30 Min. call at 6:01 pm, June 30, 2023",
    scheduled_by: "Client",
    status: "Completed",
    engagement_date: "Dec. 26, 2023",
  },
  {
    client_id: "18",
    client_name: "Lenny Herzog",
    company_name: "Blanda and Sons",
    timestamp: "30 Min. call at 6:01 pm, June 30, 2023",
    scheduled_by: "Coach",
    status: "Completed",
    engagement_date: "Dec. 26, 2023",
  },
  {
    client_id: "17",
    client_name: "Jude Harris",
    company_name: "Carroll, Windler and Shanahan",
    timestamp: "30 Min. call at 6:01 pm, June 30, 2023",
    scheduled_by: "Coach",
    status: "Waiting for feedback",
    engagement_date: "Dec. 26, 2023",
  },
];
